/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProfileImp;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Profile;

/**
 *
 * @author Windows 10 Pro
 */
public class ProfileView extends javax.swing.JFrame {

    DefaultTableModel mol = new DefaultTableModel();
    ProfileImp service = new ProfileImp();
    List<String> listDanhMuc = new ArrayList<>();
    int index = -1;

    /**
     * Creates new form ProfileView
     */
    public ProfileView() {
        initComponents();
        setLocationRelativeTo(null);
        loadCbo();
        fillTable(service.getAll());
    }

    Profile saves() {
        String ten, nhomMau, queQuan;
        float thuNhap;
        ten = txtHoTen.getText();
        thuNhap = Float.parseFloat(txtThuNhap.getText());
        if (rdA.isSelected()) {
            nhomMau = "A";
        } else if (rdB.isSelected()) {
            nhomMau = "B";
        } else if (rdAB.isSelected()) {
            nhomMau = "AB";
        } else {
            nhomMau = "O";
        }
        queQuan = (String) cboDanhMuc.getSelectedItem();
        return new Profile(ten, thuNhap, nhomMau, queQuan);
    }

    public void fillTable(List<Profile> list) {
        mol = (DefaultTableModel) tblProfile.getModel();
        mol.setRowCount(0);
        for (Profile profile : list) {
            mol.addRow(profile.toData());
        }
    }
   public void clear(){
       index=tblProfile.getSelectedRow();
       txtHoTen.setText("");
       txtThuNhap.setText("");
       cboDanhMuc.setSelectedIndex(0);
   }
    public boolean validates() {
        if (txtHoTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập họ tên");
            return false;
        }
        if (txtThuNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thu nhập");
            return false;
        }
        try {
            float thuNhap = Float.parseFloat(txtThuNhap.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thu nhâp phải là số");
            return false;
        }
        return true;
    }

    public void disPlay() {
        index = tblProfile.getSelectedRow();
        txtHoTen.setText(tblProfile.getValueAt(index, 0).toString());
        txtThuNhap.setText(tblProfile.getValueAt(index, 1).toString());
        if (tblProfile.getValueAt(index, 2).toString().equalsIgnoreCase("A")) {
            rdA.setSelected(true);
        } else if (tblProfile.getValueAt(index, 2).toString().equalsIgnoreCase("B")) {
            rdB.setSelected(true);
        } else if (tblProfile.getValueAt(index, 2).toString().equalsIgnoreCase("AB")) {
            rdAB.setSelected(true);
        } else {
            rdO.setSelected(true);
        }
        cboDanhMuc.setSelectedItem(tblProfile.getValueAt(index, 3).toString());
    }

    public void loadCbo() {
        listDanhMuc.add("Ninh Binh");
        listDanhMuc.add("Thai Binh");
        listDanhMuc.add("Nam Dinh");
        listDanhMuc.add("Nghe An");
        listDanhMuc.add("Ha Noi");
        cboDanhMuc.removeAllItems();
        for (String string : listDanhMuc) {
            cboDanhMuc.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtThuNhap = new javax.swing.JTextField();
        rdA = new javax.swing.JRadioButton();
        rdB = new javax.swing.JRadioButton();
        cboDanhMuc = new javax.swing.JComboBox<>();
        rdAB = new javax.swing.JRadioButton();
        rdO = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnResert = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfile = new javax.swing.JTable();
        btnDoc = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ Tên");

        jLabel2.setText("Thu Nhập");

        jLabel3.setText("Nhóm Máu");

        jLabel4.setText("Quê Quán");

        buttonGroup1.add(rdA);
        rdA.setText("A");

        buttonGroup1.add(rdB);
        rdB.setText("B");

        cboDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdAB);
        rdAB.setText("AB");

        buttonGroup1.add(rdO);
        rdO.setText("O");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnResert.setText("Resert");
        btnResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResertActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp Xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm theo nhóm máu");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        tblProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Họ tên", "Thu nhập", "Nhóm máu", "Quê quán"
            }
        ));
        tblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProfile);

        btnDoc.setText("Đọc file");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHoTen)
                                .addComponent(txtThuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdA)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdAB))
                                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdO)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnSapXep))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDelete)
                                            .addComponent(btnResert))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnQuayLai)
                                            .addComponent(btnDoc)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnTim))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnSapXep))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtThuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)
                    .addComponent(btnDoc))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdA)
                    .addComponent(rdB)
                    .addComponent(rdAB)
                    .addComponent(rdO)
                    .addComponent(btnResert)
                    .addComponent(btnQuayLai))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfileMouseClicked
        // TODO add your handling code here:
        disPlay();
    }//GEN-LAST:event_tblProfileMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        index = tblProfile.getSelectedRow();
        service.xoa(index);
        fillTable(service.getAll());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       if(validates()){
            if(index==-1){
            Profile pf=saves();
            service.them(pf);
            JOptionPane.showMessageDialog(this, "Đã thêm");
            fillTable(service.getAll());
                try {
                    String paths="D:\\Profile.txt";
                    File files=new File(paths);
                    if(!files.exists()){
                        files.createNewFile();
                    }
                    else{
                        service.ghiFile(paths);
                        JOptionPane.showMessageDialog(this, "Đã Ghi");
                    }
                } catch (Exception e) {
                }
        }else{
            index=tblProfile.getSelectedRow();
            Profile pf=saves();
            service.sua(index, pf);
            JOptionPane.showMessageDialog(this, "Đã sửa");
            fillTable(service.getAll());
        }
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResertActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResertActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        service.sapXep(service.getAll());
        fillTable(service.getAll());
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String tens=JOptionPane.showInputDialog(this,"Nhập nhóm máu cần tìm");
        fillTable(service.timKiem(tens));
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        try {
            String paths="D:\\Profile.txt";
            File files=new File(paths);
            if(!files.exists()){
                JOptionPane.showMessageDialog(this, "File không tồn tại");
            }
            else{
                service.docFile(paths);
                JOptionPane.showMessageDialog(this, "Đã đọc");
                fillTable(service.getAll());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        fillTable(service.getAll());
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnResert;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdA;
    private javax.swing.JRadioButton rdAB;
    private javax.swing.JRadioButton rdB;
    private javax.swing.JRadioButton rdO;
    private javax.swing.JTable tblProfile;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtThuNhap;
    // End of variables declaration//GEN-END:variables
}
